version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.14.1
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

commands:
  attach:
    steps:
      - attach_workspace:
          at: ~/workspace
  persist:
    steps:
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*

jobs:
  setup:
    executor:
      name: default
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn -v)"
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: |
            yarn setup
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist
  lint:
    executor:
      name: default
    steps:
      - attach
      - run:
          name: Lint
          command: |
            yarn lint --format junit --output-file reports/eslint/results.xml
      - store_artifacts:
          path: reports
      - store_test_results:
          path: reports
  build:
    executor:
      name: default
    steps:
      - attach
      - run:
          name: Build
          command: |
            yarn build
  deploy:
    executor:
      name: default
    parameters:
      stage:
        type: enum
        enum: [ "dev", "qas", "prd" ]
    steps:
      - attach
      - deploy:
          command: |
            yarn deploy --stage << parameters.stage >>


workflows:
  build-deploy-flow:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          context: sora-kagami
          requires:
            - setup
      - deploy:
          stage: dev
          context: sora-kagami
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          stage: qas
          context: sora-kagami
          requires:
            - build
          filters:
            branches:
              only: stable
      - deploy:
          stage: prd
          context: sora-kagami
          requires:
            - build
          filters:
            branches:
              only: production
