name: Pull Request

on: pull_request

env:
  TZ: 'Asia/Tokyo'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12, 14 ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3.0.1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: |
          yarn setup

      - run: |
          yarn lint --format junit --output-file reports/eslint/results.xml

      - uses: actions/upload-artifact@v2
        with:
          name: lint-report-on-nodejs${{ matrix.node-version }}
          path: reports

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12, 14 ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3.0.1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: |
          yarn setup

      - run: |
          yarn build

  # TODO: Commented out because the "deploy" workflow event is not fired after merging.
  #       Can be triggered by using PAT (Personal Access Token), but PAT should be avoided.
  #
  # auto-merge:
  #   if: github.actor == 'dependabot[bot]'
  #   needs: [ lint, build ]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/github-script@v3
  #       with:
  #         script: |
  #           github.pulls.createReview({
  #             event: 'APPROVE',
  #             owner: context.payload.repository.owner.login,
  #             repo: context.payload.repository.name,
  #             pull_number: context.payload.pull_request.number
  #           })
  #           github.pulls.merge({
  #             merge_method: 'rebase',
  #             owner: context.payload.repository.owner.login,
  #             repo: context.payload.repository.name,
  #             pull_number: context.payload.pull_request.number
  #           })
